---
Name: forager-bifrost
Only:
  envvarset: 'BIFROST_MANAGEMENT_API_KEY'
After:
  - 'silverstripe-forager-elastic-enterprise'
  - 'search-forager-default'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\SearchService\Service\IndexConfiguration:
    constructor:
      index_variant: '`BIFROST_ENGINE_PREFIX`'
  SilverStripe\SearchService\Interfaces\IndexingInterface:
    class: SilverStripe\ForagerBifrost\Service\BifrostService
    constructor:
      client: '%$Elastic\EnterpriseSearch\Client'
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'
      builder: '%$SilverStripe\SearchService\Service\DocumentBuilder'
  Elastic\EnterpriseSearch\Client:
    factory: SilverStripe\ForagerBifrost\Service\ClientFactory
    constructor:
      host: '`BIFROST_ENDPOINT`'
      token: '`BIFROST_MANAGEMENT_API_KEY`'
      http_client: '%$GuzzleHttp\Client'
  Elastic\EnterpriseSearch\AppSearch\Request\GetSchema:
    class: SilverStripe\ForagerBifrost\Service\Requests\GetSchema

## customise the dataobject fields for Bifrost compatability
SilverStripe\SearchService\DataObject\DataObjectDocument:
  id_field: record_id
  base_class_field: record_base_class
  page_content_field: page_content
