---
Name: forager-bifrost
Only:
  envvarset: 'BIFROST_MANAGEMENT_API_KEY'
After:
  - 'search-forager-default'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Forager\Service\IndexConfiguration:
    constructor:
      indexPrefix: '`BIFROST_ENGINE_PREFIX`'
  SilverStripe\Forager\Interfaces\IndexingInterface:
    class: SilverStripe\ForagerBifrost\Service\BifrostService
    constructor:
      client: '%$Silverstripe\Search\Client\Client.managementClient'
      configuration: '%$SilverStripe\Forager\Service\IndexConfiguration'
      builder: '%$SilverStripe\Forager\Service\DocumentBuilder'
  Silverstripe\Search\Client\Client.managementClient:
    factory: SilverStripe\ForagerBifrost\Service\ClientFactory
    constructor:
      host: '`BIFROST_ENDPOINT`'
      token: '`BIFROST_MANAGEMENT_API_KEY`'
      httpClient: '%$GuzzleHttp\Client'
