---
Name: search-service-bifrost
After:
    - 'silverstripe-search-service-dataobject'
    - 'search-service-default'
---
SilverStripe\Core\Injector\Injector:
    SilverStripe\SearchService\Service\IndexConfiguration:
        constructor:
            index_variant: '`BIFROST_ENGINE_PREFIX`'
    SilverStripe\SearchService\Interfaces\IndexingInterface:
        class: SilverStripe\SearchServiceBifrost\Service\BifrostService
    Elastic\EnterpriseSearch\Client.indexingInterface:
        factory: SilverStripe\SearchServiceBifrost\Service\ClientFactory
        constructor:
            host: '`BIFROST_ENDPOINT`'
            token: '`BIFROST_PRIVATE_API_KEY`'
            http_client: '%$GuzzleHttp\Client'

## customise the dataobject fields for Bifrost compatability
SilverStripe\SearchService\DataObject\DataObjectDocument:
    id_field: record_id
    base_class_field: record_base_class
    page_content_field: page_content
